### ISSUE TITLE
Cycler causing problems for building conda package

### ISSUE THREAD

**Issue by desilinguist** [conda-forge/cycler-feedstock#13]
Issue: I am building a conda package that relies on `seaborn` which relies on `matplotlib` and hence `cycler`. I am building with `conda-forge` as the primary channel and I see that the generic `cycler==0.10.0-py_1` package gets installed during the build process. However, when `python setup.py install` runs in the build, it still tries to download `cycler` even though it's already installed. I looked in the build environment and it looks like the `.egg-info` file is incorrect. For example, in my Python 3.7 build environment, I see the following file: `cycler-0.10.0-py2.7.egg-info` which is probably why `pip` doesn't recognize that `cycler` is already installed. 

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : base
    active env location : /Users/nmadnani/anaconda
            shell level : 1
       user config file : /Users/nmadnani/.condarc
 populated config files : /Users/nmadnani/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.10
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/nmadnani/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/desilinguist/osx-64
                          https://conda.anaconda.org/desilinguist/noarch
          package cache : /Users/nmadnani/anaconda/pkgs
                          /Users/nmadnani/.conda/pkgs
       envs directories : /Users/nmadnani/anaconda/envs
                          /Users/nmadnani/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment]
> However, when python setup.py install

The recommended way to install python packages in a conda recipe is with `script: "{{ PYTHON }} -m pip install . --no-deps -vv"`. However, the cycler recipe could use an update and that could be solved as soon as the new versionis up.

**Comment by desilinguist** [comment]
That's good to know, @ocefpaf! I was going by all of the sample pure python recipes examples in the conda build documentation and none of them mention this. Thanks!
